# Generated by Django 2.1.8 on 2020-04-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Truecaller', '0002_auto_20200420_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contact',
        ),
    ]
