# Generated by Django 2.1.8 on 2020-04-22 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Truecaller', '0005_auto_20200421_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='mapusercontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Truecaller.Contact'),
        ),
    ]
